### Exercicio 1

<small>
Encontre a inversa das matrizes abaixo. Use o método np.linalg.inv().
<small>

In [1]:
import numpy as np

In [2]:
A = np.array([[1,2],[3,4]])
B = np.array([[-1,3],[5,4]])

In [5]:
inv_a = np.linalg.inv(A)
inv_b = np.linalg.inv(B)

In [6]:
print(inv_a)
print(inv_b)

[[-2.   1. ]
 [ 1.5 -0.5]]
[[-0.21052632  0.15789474]
 [ 0.26315789  0.05263158]]


### Exercicio 2

<small>
Encontre a inversa da matriz A:
<small>

In [7]:
A = np.array([[4,-1,2,-2],[3,-1,0,0],[2,3,1,0],[0,7,1,1]])
inv_a = np.linalg.inv(A)
print(inv_a)


[[ -1.  -1.   4.  -2.]
 [ -3.  -4.  12.  -6.]
 [ 11.  14. -43.  22.]
 [ 10.  14. -41.  21.]]


### Exercicio 3

<small>
Encontre a inversa da matriz A:
<small>

In [8]:
A = np.diag([7,8,11,2,4,5,1,3])
inv_a = np.linalg.inv(A)
print(inv_a)

[[0.14285714 0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.125      0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.09090909 0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.5        0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.25       0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.2
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  1.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.33333333]]
