### Exercício 1

<small>
Defina as matrizes abaixo utilizando o NumPy. Use o método np.array().
<small>

In [1]:
import numpy as np

In [3]:
A = np.array([[1,2,3],[2,1,-1]])
print(A)

[[ 1  2  3]
 [ 2  1 -1]]


In [4]:
B = np.array([[1,-2,0],[3,0,1],[4,5,6]])
print(B)

[[ 1 -2  0]
 [ 3  0  1]
 [ 4  5  6]]


In [7]:
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
C = np.array(range(1,10)).reshape(3,3)
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
D = np.array([[1],[4],[-3]])
print(D)

[[ 1]
 [ 4]
 [-3]]


### Exercício 2

<small>
Defina as matrizes abaixo utilizando o NumPy. Use o método np.array().
<small>

In [13]:
E = np.array(range(1,7)).reshape(6,1)
print(E)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [10]:
F = np.array([1,0,3,-10])
print(F)

[  1   0   3 -10]


In [11]:
G = np.array(range(1,6))
print(G)

[1 2 3 4 5]


### Exercício 3

<small>
Defina as matrizes abaixo utilizando o NumPy. Use o método np.array().
<small>

In [18]:
A = np.zeros(shape=(2,2))
print(A)

[[0. 0.]
 [0. 0.]]


In [19]:
B = np.zeros(shape=(3,5))
print(B)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [20]:
C = np.ones(shape=(5,5))
print(C)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
I2 = np.identity(2)
print(I2)

[[1. 0.]
 [0. 1.]]


In [24]:
I3 = np.identity(3)
print(I3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
I6 = np.identity(6)
print(I6)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


### Exercício 4

<small>
Defina a matrizes triangulares abaixo utilizando o NumPy. Use os métodos np.triu() e np.tril().
<small>

In [30]:
A = np.triu(np.arange(1,10).reshape(3,3),k=0)
print(A)

[[1 2 3]
 [0 5 6]
 [0 0 9]]


In [31]:
B = np.tril(np.arange(1,10).reshape(3,3),k=0)
print(B)

[[1 0 0]
 [4 5 0]
 [7 8 9]]


In [34]:
C = np.triu(np.arange(100,125).reshape(5,5),k=0)
print(C)

[[100 101 102 103 104]
 [  0 106 107 108 109]
 [  0   0 112 113 114]
 [  0   0   0 118 119]
 [  0   0   0   0 124]]


### Exercício 5

<small>
Defina as matrizes abaixo utilizando o NumPy. Use os métodos np.diag() e np.array().
<small>

In [36]:
A = np.diag([7,1,-1])
print(A)

[[ 7  0  0]
 [ 0  1  0]
 [ 0  0 -1]]


In [42]:
B= np.diag(np.full(4,3))
B = np.diag([3]*4)
print(B)

[[3 0 0 0]
 [0 3 0 0]
 [0 0 3 0]
 [0 0 0 3]]


In [41]:
C = np.diag(range(-5,0,1))
print(C)

[[-5  0  0  0  0]
 [ 0 -4  0  0  0]
 [ 0  0 -3  0  0]
 [ 0  0  0 -2  0]
 [ 0  0  0  0 -1]]
