### Exercicio 1

<small>
Podemos obter a transposta de uma matriz permutando as linhas pelas colunas de mesmo índice(ou seja, o que é linha se transforma em coluna e o que é coluna se transforma em linha). Obtenha a Matriz transposta das matrizes a seguir:
<small>

In [1]:
import numpy as np

In [3]:
A=np.array([[1,-3,2],[2,1,-3],[4,-3,-1]])
B = np.array([[1,0,4],[-7,5,5],[25,9,11]])
print(A.T)
print(B.transpose())

[[ 1  2  4]
 [-3  1 -3]
 [ 2 -3 -1]]
[[ 1 -7 25]
 [ 0  5  9]
 [ 4  5 11]]
