### Exercicio 1

<small>
Resolva os sistemas lineares a seguir. Utilize o método np.linalg.solve().
<small>

In [1]:
import numpy as np

In [8]:
A = np.array([[2,3],[1,-1]])
B = np.array([[6],[8]])
print(A)
print(B)

[[ 2  3]
 [ 1 -1]]
[[6]
 [8]]


In [4]:
solucao = np.linalg.solve(A,B)
print(solucao)

[[ 6.]
 [-2.]]


In [6]:
A = np.array([[3,1],[1,2]])
B = np.array([[9],[8]])

In [7]:
solucao = np.linalg.solve(A,B)
print(solucao)

[[2.]
 [3.]]


#### Exercicio 2

<small>
Resolva o sistema linear abaixo.
<small>

In [12]:
A = np.array([[1,0,3],[2,-4,0],[3,-2,-5]])
B = np.array([[-8],[-4],[26]])
print(A)
print(B)

[[ 1  0  3]
 [ 2 -4  0]
 [ 3 -2 -5]]
[[-8]
 [-4]
 [26]]


In [13]:
solucao = np.linalg.solve(A,B)
print(solucao)

[[ 4.]
 [ 3.]
 [-4.]]


### Exercicio 3

<small>
Resolva o sistema linear abaixo. Utilize o método np.linalg.solve().
<small>

In [14]:
A = np.array([[1,1,1,1],[1,1,1,-1],[1,1,-1,1],[1,-1,1,1]])
B = np.array([[0],[4],[-4],[2]])
print(A)
print(B)

[[ 1  1  1  1]
 [ 1  1  1 -1]
 [ 1  1 -1  1]
 [ 1 -1  1  1]]
[[ 0]
 [ 4]
 [-4]
 [ 2]]


In [15]:
solucao = np.linalg.solve(A,B)
print(solucao)

[[ 1.]
 [-1.]
 [ 2.]
 [-2.]]


### Exercicio 4

<small>
Resolva o sistema linear abaixo.
<small>

In [20]:
A = np.array([[3,2,0],[1, -1, 0],[0,5,1]])
B = np.array([[2],[4],[-1]])
B = np.array([2, 4, -1])
print(A)
print(B)

[[ 3  2  0]
 [ 1 -1  0]
 [ 0  5  1]]
[ 2  4 -1]


In [21]:
solucao = np.linalg.solve(A,B)
print(solucao)

[ 2. -2.  9.]
