### Exercício 1

<small>
Defina as matrizes A e B dadas a seguir e obtenha A+B.
<small>

In [1]:
import numpy as np

In [3]:
A = np.array([[10,11],[5,1],[-2,4]])
B = np.array([[1,25],[3,4],[0,-10]])
print(A)
print(B)

[[10 11]
 [ 5  1]
 [-2  4]]
[[  1  25]
 [  3   4]
 [  0 -10]]


In [4]:
C = A + B
print(C)

[[11 36]
 [ 8  5]
 [-2 -6]]


### Exercício 2

In [5]:
A = np.array([[10,11],[5,1],[-2,4]])
B = np.array([[1,25],[3,4],[0,-10]])
C = np.array([[7,3],[6,1],[0,0]])

In [7]:
d =  A + B
d1 = B + A
print(d == d1)

[[ True  True]
 [ True  True]
 [ True  True]]


In [8]:
ass = A + (B + C)
ass1 = (A+B)+C
print(ass==ass1)

[[ True  True]
 [ True  True]
 [ True  True]]


In [9]:
print(A+0 == A)

[[ True  True]
 [ True  True]
 [ True  True]]


In [10]:
zero = np.zeros(shape=(3,2))
print(A+B==B+A)
print((A+(B+C))==((A+B)+C))
print(A+zero==A)

[[ True  True]
 [ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]
 [ True  True]]


### Exercícios 3

<small>
Sejam as matrizes definidas a seguir, calculemos o que se pede na sequência.

A+B

A.C (multiplicação de matrizes)

B.C

C.D

D.A

D.B

-A

-D

2A+3B

Este exercício é uma adaptção de BOLDRINI, J. et al. Álgebra Linear. São Paulo: Harbra, 1986.
<small>

In [11]:
A=np.array([[1,2,3],[2,1,-1]])
B=np.array([[-2,0,1],[3,0,1]])
C=np.array([[-1],[2],[4]])
D=np.array([[2,-1]])

In [14]:
print(A+B)
print(A.dot(C))
print(B.dot(C))
print(C.dot(D))
print(D.dot(A))
print(D.dot(B))
print((-1)*(A))
print((-1)*(D))
print(2*A+3*B)


[[-1  2  4]
 [ 5  1  0]]
[[15]
 [-4]]
[[6]
 [1]]
[[-2  1]
 [ 4 -2]
 [ 8 -4]]
[[0 3 7]]
[[-7  0  1]]
[[-1 -2 -3]
 [-2 -1  1]]
[[-2  1]]
[[-4  4  9]
 [13  2  1]]


### Exercício 4

<small>
Sejam as matrizes A,B e C. Mostre que:
<small>

In [15]:
A=np.array([[1,-3,2],[2,1,-3],[4,-3,-1]])
B=np.array([[1,4,1,0],[2,1,1,1],[1,-2,1,2]])
C=np.array([[2,1,-1,-2],[3,-2,-1,-1],[2,-5,-1,0]])
print(A.dot(B)==A.dot(C))

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
